// Generated by CoffeeScript 1.6.3
(function() {
  var Upload, fs, path, util, winston;

  fs = require("fs");

  winston = require("winston");

  path = require("path");

  util = require("util");

  mime = require('mime');

  checksum = require('checksum')

  Upload = (function() {
    function Upload(config, fileId) {
      this.fileId = fileId;
      this.filePath = path.join(config.files, fileId);
      this.infoPath = path.resolve("" + this.filePath + ".json");
      this.info = null;
    }

    Upload.prototype.create = function(requestInfo) {
      var error, info;
      try {
        fs.closeSync(fs.openSync(this.filePath, 'w'));
      } catch (_error) {
        error = _error;
        winston.error(util.inspect(error));
        return {
          error: [500, "Create Failed"]
        };
      }
      try {
        info = {
          state: "created",
          createdOn: Date.now(),
          offset: 0,
          finalLength : parseInt(requestInfo["final-length"]),
        };

        for (var key in requestInfo) {
          info[key] = requestInfo[key]
        }

        info['content-type'] = mime.lookup(requestInfo["real-name"])

        fs.writeFileSync(this.infoPath, JSON.stringify(info, null, 2));
        this.info = info;
      } catch (_error) {
        error = _error;
        winston.error(util.inspect(error));
        return {
          error: [500, "Create Failed - Metadata"]
        };
      }
      return {
        info: this.info
      };
    };

    Upload.prototype.save = function() {
      var error;
      try {
        fs.writeFileSync(this.infoPath, JSON.stringify(this.info, null, 2));
      } catch (_error) {
        error = _error;
        winston.error(util.inspect(error));
        return {
          error: [500, "Save Failed - Metadata"]
        };
      }
      return {
        info: this.info
      };
    };

    Upload.prototype.load = function() {
      var e, error, stat;
      if (!fs.existsSync(this.filePath)) {
        return {
          error: [404, "File Not Found"]
        };
      }
      try {

        this.info = require(this.infoPath);
        console.log(this.info)
      } catch (_error) {
        error = _error;
        winston.error(util.inspect(error));
        return {
          error: [404, "Not Found - Metadata"]
        };
      }
      try {
        stat = fs.statSync(this.filePath);
        this.info.offset = stat.size;
      } catch (_error) {
        e = _error;
        winston.error("file error " + fileId + " " + (util.inspect(e)));
        return {
          error: [500, "File Load Error"]
        };
      }

      this.info.filePath = this.filePath

      return {
        info : this.info
      }

      //checksum.file(this.filePath, function(err, sum){
        //var info = this.info || {}
        //info['sum'] = sum
        //return info 

        //console.log(this.info)

      //})


      /*checksum.file(this.filePath, function(err, sum){
        this.info.sum = sum;
        return {
          info: this.info
        };
      })*/
    };

    Upload.prototype.stream = function() {
      return fs.createReadStream(this.filePath);
    };

    return Upload;

  })();

  exports.Upload = function(config, fileId) {
    return new Upload(config, fileId);
  };

}).call(this);
